name          'sdodson-secretbox'
version '0.1.4'
source        'https://github.com/sdodson/puppet-secretbox'
author        'evaryont,sdodson'
license       'Apache License, Version 2.0'
summary       'Consistent, predictable random values'
description   'A custom function to randomly generate a value once and return the same value for every invocation, per index.'
project_page  'https://github.com/sdodson/puppet-secretbox'
